GestionVehicular/Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionVehicular.Models;
using GestionVehiculos.Context;
using OfficeOpenXml;
using System.Net.Mime;

namespace GestionVehicular.Controllers
{
    public class ReporteController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReporteController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reporte vehiculo
        [Authorize]
        public async Task<IActionResult> Index(DateTime? fechaInicio, DateTime? fechaFin)
        {
            var applicationDbContext = _context.Repuestos.AsQueryable();

            if (fechaInicio.HasValue)
            {
                applicationDbContext = applicationDbContext.Where(s => s.Mantenimiento.FechaCreacion >= fechaInicio);
            }

            if (fechaFin.HasValue)
            {
                applicationDbContext = applicationDbContext.Where(s => s.Mantenimiento.FechaCreacion <= fechaFin);
            }

            applicationDbContext = applicationDbContext.Include(s => s.Mantenimiento.TipoMantenimiento).Include(s => s.Mantenimiento.Usuario).Include(s => s.Mantenimiento.Vehiculo);

            return View(await applicationDbContext.ToListAsync());

        }

        // POST: Sugerencias/ExportarExcel        
        /* public async Task<IActionResult> ExportarExcel(DateTime? fechaInicio, DateTime? fechaFin)
        {
            var applicationDbContext = _context.Sugerencias.AsQueryable();

            if (fechaInicio.HasValue)
            {
                applicationDbContext = applicationDbContext.Where(s => s.Fecha >= fechaInicio);
            }

            if (fechaFin.HasValue)
            {
                applicationDbContext = applicationDbContext.Where(s => s.Fecha <= fechaFin);
            }

            applicationDbContext = applicationDbContext.Include(s => s.Circuito).Include(s => s.Subcircuito).Include(s => s.TipoSugerencia);

            var sugerencias = await applicationDbContext.ToListAsync();

            var report = (from s in sugerencias
                          group s by new
                          {
                              TipoSugerenciaNombre = s.TipoSugerencia.Nombre,
                              CircuitoNombre = s.Circuito.Nombre,
                              SubcircuitoNombre = s.Subcircuito.Nombre,
                          } into g
                          select new
                          {
                              FechaInicio = fechaInicio.ToString(),
                              FechaFin = fechaFin.ToString(),
                              Cantidad = g.Count(),
                              Tipo = g.Key.TipoSugerenciaNombre,
                              Circuito = g.Key.CircuitoNombre,
                              Subcircuito = g.Key.SubcircuitoNombre,
                          }
                          ).ToList();

            using var package = new ExcelPackage();

            var worksheet = package.Workbook.Worksheets.Add("SugerenciasReclamos");

            worksheet.Cells["A1"].LoadFromCollection(report, PrintHeaders: true);

            for (var col = 1; col < report.Count + 1; col++)
                worksheet.Column(col).AutoFit();

            // Convertir el paquete de Excel a un array de bytes
            byte[] fileBytes = package.GetAsByteArray();

            // Devolver el archivo de Excel al usuario
            return File(fileBytes, MediaTypeNames.Application.Octet, "sugerencias.xlsx");
        }*/
    }
}

GestionVehicular/Views/Reporte/Index.cshtml
@model IEnumerable<GestionVehicular.Models.Repuesto>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-secondary">Reportes de Mantenimiento</h1>
<hr />
@using (Html.BeginForm("Index", "Reporte", FormMethod.Get, new { id = "reportForm" }))
{
    <div class="container-fluid">
        <div class="row">
            <div class="col-4">
                Fecha inicio: @Html.TextBox("fechaInicio", null, new { @class = "form-control", type = "date", id = "fechaInicio" })
            </div>
            <div class="col-4">
                Fecha fin: @Html.TextBox("fechaFin", null, new { @class = "form-control", type = "date",  id = "fechaFin" })
            </div>
            <div class="col-2" style="display: none">
                <br>
                <input type="submit" value="Filtrar" class="btn btn-success" />
            </div>
            <div class="col-2">
                <br>
                @Html.ActionLink("Exportar Reporte", "ExportarExcel", null, null, new { @class = "btn btn-primary", id = "exportarExcel" })
            </div>
        </div>
    </div>
}
<hr />
<table class="table table-sm">
    <thead class="table-primary">
        <tr>
            <th>
                        @Html.DisplayNameFor(model => model.Mantenimiento.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Mantenimiento.Kilometraje)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Mantenimiento.Observacion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Mantenimiento.Usuario)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Mantenimiento.Vehiculo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Mantenimiento.TipoMantenimiento)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cost)
                    </th>
                    <th>
                        Activo
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Mantenimiento.FechaCreacion)
                    </th>
                    <th>
                        Estado de Solicitud
                    </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mantenimiento.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mantenimiento.Kilometraje)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mantenimiento.Observacion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mantenimiento.Usuario.Nombre) 
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mantenimiento.Vehiculo.Placa)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mantenimiento.TipoMantenimiento.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cost)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mantenimiento.EsActivo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mantenimiento.FechaCreacion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mantenimiento.Aprobacion.Estado)
                        </td>
            </tr>        

        }
<html>
    <table>
        <thead>
            <tr>
                <th>Costo Total:</th>
                @* <th>Precio</th *@
            </tr>
        </thead>
        @* <tbody>
            @* @foreach (var producto in Model)
            {
                <tr>
                    <td>@producto.Nombre</td>
                    <td>@producto.Cost</td>
                </tr>
            }  
        </tbody> *@
    </table>

    @if ( Model.Sum(p => p.Cost) > 0)
    {
        var sumaPrecios = Model.Sum(p => p.Cost);
        <p>El costo total por mantenimiento es: @sumaPrecios</p>
    }
    else
    {
        <p>No exite valores a sumar.</p>
    }
    </tbody>
</table>





@* @section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // Función para exportar a Excel
        $(document).ready(function () {
            $('#exportarExcel').click(function (event) {
                event.preventDefault();  // Detener la acción predeterminada del enlace
                var url = $(this).attr('href');  // Obtener la URL original del enlace
                var fechaInicio = $('#fechaInicio').val();
                var fechaFin = $('#fechaFin').val();
                // Agregar las fechas a la URL como parámetros de consulta
                url += '?fechaInicio=' + fechaInicio + '&fechaFin=' + fechaFin;
                window.location.href = url;  // Redireccionar al usuario a la nueva URL
            });
        });
        // Función para enviar el formulario cuando se cambie la fecha
        $(document).ready(function () {
            $('#fechaInicio, #fechaFin').change(function () {
                $('#reportForm').submit();
            });
        });
    </script>

} *@